### ISSUE TITLE
Patterns are misinterpreted by TV when using the universal-mode (HTC One M8 - CM 12.1)

### ISSUE THREAD

**Issue by JasperWeiss** [42SK/TVKILL#8] opened 2015-10-27 17:28 UTC
Hi, 
I tried this app with my phone on 2 Sony TV's
But neither worked. It did detect my IR blaster so it should work.
Can you confirm whether it should work on my setup? It seems like I'm having the same issue as the guy running CM on his LG G2

**Comment by 42SK** [comment] 2015-10-27 18:47
There already was a review on Google Play which implied that TV KILL wouldn’t work on certain HTC devices. I guess you've just confirmed it.
The main problem seems to be almost equivalent to the one on LG devices:
* HTC also wants to distribute [it's own API](https://www.htcdev.com/devcenter/opensense-sdk/legacy-apis/htc-ir-api/) and therefore doesn’t support Android's [ConsumerIrManager](http://developer.android.com/reference/android/hardware/ConsumerIrManager.html). One should mention that HTC's API is already marked as "legacy", which makes it hard to tell if implementing it would solve the problem on a long-term basis.
* Once again, I am not certain if the API can be used along with the [GPLv3 licence](https://www.gnu.org/licenses/gpl-3.0) which TV KILL uses.
* And of course I also can't say for certain that the API would work on devices running CyanogenMod.

However, there is one thing that I find curious. If HTC really wouldn't support the entire ConsumerIrManager class, then the application shouldn't be detecting your IR-blaster, since it uses the *hasIrEmitter()* method from that class to do that. So maby there is a way to use the IR-blaster on your device with the ConsumerIrManager, but of course it is also possible to that HTC merely disabled the *transmit()* method.

If anyone knows more on this topic or thinks that he might be able to help sorting out the licence issues, please comment!

**Comment by JasperWeiss** [comment] 2015-10-27 19:53
Allright, so it does actually work. It's just that the universal tab doesn't. Going to brands and hitting sony off multiple times does the trick somehow. I'm not sure if the transmitter isn't strong enough or anything. But I need to keep hitting off while aiming it directly at the tv's receiver.
Is there anything that can be done about this software wise?

**Comment by JasperWeiss** [comment] 2015-10-27 20:00
Aha I see. So I only need to hit off once, but the TV seems to wait a sec and a half or so to see if that was the only signal. Probably to prevent a range of singals giving it unintended commands or something.
So the universal tab, which sends a whole bunch of signals right after won't work. It needs to be specifically that signal only.

Same witht the remote, pressing off and next program right after will result in it going to the next program ignoring the off signal.

Perhaps there should be a longer delay between sending the commands?

**Comment by 42SK** [comment] 2015-10-27 21:23
Oh, great!
That should be much easier to fix.
It's good to know that TV KILL does work on at least some HTC devices.
I was always wondering if the TVs could somehow misinterpret the commands when the patterns are transmitted directly one after another, but it somehow never caused me any problems.
I'll probably add a option in the application's settings that lets you adjust the delay between the individual patterns, that should do the trick.

**Comment by 42SK** [comment] 2015-10-28 17:29
This should be fixed in version 1.0.8.
You can adjust the delay between the individual patterns in the settings.

**Closed by 42SK** 2015-10-28 17:29 UTC
Labels: bug
