### ISSUE TITLE
OnePlus2 / CyanogenMod 12.1

### ISSUE THREAD

**Issue by beerisgood** [42SK/TVKILL#12] opened 2016-02-21 19:51 UTC
Have you app any requirements? Because with my OnePlus 2 and CyanogenMod 12.1 which is Android 5.1 i can't install the app via F-Droid.
Its grey and the download/ install button doesn't exist

**Comment by 42SK** [comment] 2016-02-21 20:07
This is a duplicate of issue #3.
F-Droid doesn't let you install **TV KILL** on devices that are not equipped with a build-in infrared blaster (such as the OnePlus 2), since they don't fulfill the necessary hardware requirements.

**Closed** 2016-02-21 20:07 UTC
Labels: duplicate
